# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
require "faker"

puts "Seeding users..."
Petsitter.create!(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, email: Faker::Internet.email, phone_number: Faker::PhoneNumber.phone_number, description: "Welcome to Alice's Pet Paradise! I'm Alice, a seasoned and compassionate petsitter with a genuine love for all animals. With years of experience, I've created a haven for your furry friends. Your pets will enjoy a cozy and pet-friendly space with personalized attention. Whether it's a playful session, a relaxing nap, or a nutritious meal, I ensure your pets feel right at home. Regular updates and open communication are my priorities, so you can travel with peace of mind knowing your beloved pets are in capable and caring hands.", photo:"1.png", address: "53 Junction Road, London", review: "Great petsitter!", review1: "Highly recommended!", review2: "Excellent service!", rt: "⭐⭐⭐⭐")

Petsitter.create!(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, email: Faker::Internet.email, phone_number: Faker::PhoneNumber.phone_number, description: "Greetings from Bob's Pet Retreat! I'm Bob, your dedicated and reliable petsitter. My passion for animals led me to create a haven where your pets can enjoy their own vacation. With a spacious backyard for dogs to play in and cozy indoor spaces for all pets, I prioritize the well-being and happiness of your furry companions. Following your specific care instructions, I ensure a seamless and enjoyable experience for your pets, leaving you with peace of mind during your time away.", photo:"2.png", address: "13 Heneage Street, London", review: "Fantastic petsitter!", review1: "Amazing service!", review2: "Very satisfied!", rt: "⭐⭐⭐⭐")

Petsitter.create!(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, email: Faker::Internet.email, phone_number: Faker::PhoneNumber.phone_number, description: "Greetings, fellow pet lovers! I'm Dexter, the proud owner of Dexter's Purr Palace, a haven for your feline friends. With a background in veterinary care, I bring a wealth of knowledge and passion to my petsitting services. Your cats will luxuriate in a specially designed space that caters to their every whim. From interactive toys to cozy lounging spots, Dexter's Purr Palace promises a delightful retreat. I believe in a holistic approach, ensuring not just physical well-being but also mental stimulation for your beloved cats. Choose Dexter's Purr Palace for a purr-fectly tailored experience.", photo:"3.png", address: "Clifford Court, 24-25 Kensington Gardens Square, London", review: "Wonderful petsitter!", review1: "Top-notch service!", review2: "Extremely happy!", rt: "⭐⭐⭐⭐")

Petsitter.create!(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, email: Faker::Internet.email, phone_number: Faker::PhoneNumber.phone_number, description: "Woof, there! I'm Gina, the enthusiastic owner of Gina's Doggy Delight, where tails wag and smiles abound. As an avid dog lover, I've curated an environment that mirrors the joy and energy of our four-legged friends. Your dogs will revel in a mix of outdoor adventures and indoor snuggles. With a focus on positive reinforcement, I ensure a safe and playful atmosphere for every pup. Gina's Doggy Delight is not just a petsitting service; it's a canine retreat where your dogs will make friends, stay active, and return to you with a wagging tail.", photo:"4.png", address: "171 Knightsbridge, London", review: "Outstanding petsitter!", review1: "Exceptional service!", review2: "Highly impressed!", rt: "⭐⭐⭐⭐")

Petsitter.create!(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, email: Faker::Internet.email, phone_number: Faker::PhoneNumber.phone_number, description: " Greetings exotic pet enthusiasts! I'm Max, the caretaker of Max's Exotic Haven, a specialized retreat for your unique and extraordinary pets. With a background in exotic animal care, I offer a safe and enriching environment for reptiles, birds, and other non-traditional companions. From temperature-controlled habitats to carefully curated diets, Max's Exotic Haven ensures the well-being of your exotic friends. With a commitment to providing specialized care, I tailor my services to meet the distinctive needs of each exotic pet, promising a secure and content stay.", photo:"5.png", address: "129 Wilton Rd, Pimlico, London", review: "Terrific petsitter!", review1: "Superb service!", review2: "Absolutely delighted!", rt: "⭐⭐⭐⭐")

Petsitter.create!(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, email: Faker::Internet.email, phone_number: Faker::PhoneNumber.phone_number, description: "Hi there! I'm not just a petsitter; I'm a soothing presence for your cats. Let's create a stress-free and enjoyable experience for your furry family members!", photo:"6.png", address: "36a Norwood Road, London", review: "Excellent petsitter!", review1: "Great experience!", review2: "Very pleased!", rt: "⭐⭐⭐⭐")

Petsitter.create!(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, email: Faker::Internet.email, phone_number: Faker::PhoneNumber.phone_number, description: "Trust me to be your go-to petsitter! I understand that dogs have their own personalities, and I'm here to build a connection with each of them, making sure they feel secure and loved.", photo:"7.png", address: "275 Railton Road, London", review: "Amazing petsitter!", review1: "Highly recommended!", review2: "Exceptional service!", rt: "⭐⭐⭐⭐")
Petsitter.create!(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, email: Faker::Internet.email, phone_number: Faker::PhoneNumber.phone_number, description: "Greetings pet parents! I'm Carol, the proud owner of Carol's Cozy Critter Care. As a devoted petsitter, I provide a warm and loving environment for your cherished companions. With a keen understanding of different pet needs, I create a personalized experience for each furry friend. From interactive playtime to soothing cuddles, your pets receive the attention they deserve. My commitment to their well-being extends to regular updates and a flexible approach to meet their unique requirements. Rest easy knowing your pets are not only cared for but embraced with genuine affection.", photo:"8.png", address: "56 Brailsford Road, London", review: "Fantastic petsitter!", review1: "Outstanding service!", review2: "Very satisfied!", rt: "⭐⭐⭐⭐")

Petsitter.create!(first_name: Faker::Name.first_name, last_name: Faker::Name.last_name, email: Faker::Internet.email, phone_number: Faker::PhoneNumber.phone_number, description: "Greetings from Bob's Pet Retreat! I'm Bob, your dedicated and reliable petsitter. My passion for animals led me to create a haven where your pets can enjoy their own vacation. With a spacious backyard for dogs to play in and cozy indoor spaces for all pets, I prioritize the well-being and happiness of your furry companions. Following your specific care instructions, I ensure a seamless and enjoyable experience for your pets, leaving you with peace of mind during your time away.", photo:"9.png", address: "134 Mayall Road, London", review: "Bob is fantastic! My dog came back happy and well-exercised. Bob's love for animals is evident, and I appreciate the peace of mind he provides.", review1:"Bob took care of my two cats, and they seemed to have a great time. He followed all the care instructions, and I felt reassured throughout my trip.", review2:"Bob is a reliable and trustworthy petsitter. I've used his services multiple times, and my pets always return content and well-cared-for.", rt: "⭐⭐⭐")

Petsitter.create!(first_name: "Alice", last_name: "Colon", email: Faker::Internet.email, phone_number: Faker::PhoneNumber.phone_number, description: "Greetings pet parents! I'm Carol, the proud owner of Carol's Cozy Critter Care. As a devoted petsitter, I provide a warm and loving environment for your cherished companions. With a keen understanding of different pet needs, I create a personalized experience for each furry friend. From interactive playtime to soothing cuddles, your pets receive the attention they deserve. My commitment to their well-being extends to regular updates and a flexible approach to meet their unique requirements. Rest easy knowing your pets are not only cared for but embraced with genuine affection.", photo:"10.png", address: "32 Cambria Road, London", review:"Alice is amazing! She took great care of my cat while I was away. Regular updates and a happy kitty when I returned. Highly recommend!", review1: "Alice goes above and beyond for the pets she looks after. My dog had a fantastic time, and I appreciated the photo updates. Five stars!", review2:"Professional and caring petsitter. Alice genuinely loves animals, and it shows in the excellent service she provides. My go-to petsitter!", rt:"⭐⭐⭐⭐")
